package cust.bill.mgmt.bus.model;

import java.util.Objects;

/**
 * This resource is used to manage the creation request of a customer bill in real-time (on demand).
 */
public class CustomerBillOnDemand {
	
  private String id = null;

  private String href = null;

  private String name = null;

  private String description = null;

  private StateValues state = null;

  private String lastUpdate = null;

  private String type = null;

  private String schemaLocation = null;

  public BillingAccountRef billingAccount = null;

  public RelatedPartyRef relatedParty = null;

  public BillRef customerBill = null;

  public CustomerBillOnDemand id(String id) {
    this.id = id;
    return this;
  }

  /**
   * Unique identifier of the customer bill on demand request given by the server
   * @return id
  **/
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public CustomerBillOnDemand href(String href) {
    this.href = href;
    return this;
  }

  /**
   * Reference of the customer bill on demand request
   * @return href
  **/
  public String getHref() {
    return href;
  }

  public void setHref(String href) {
    this.href = href;
  }

  public CustomerBillOnDemand name(String name) {
    this.name = name;
    return this;
  }

  /**
   * Friendly name to identify the customer bill on demand request
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public CustomerBillOnDemand description(String description) {
    this.description = description;
    return this;
  }

  /**
   * Additional data describing the customer bill on demand request
   * @return description
  **/
  public String getDescription() {
    return description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public CustomerBillOnDemand state(StateValues state) {
    this.state = state;
    return this;
  }

  /**
   * State of the customer bill on demand request : rejected, inProgress, done or terminatedWithError
   * @return state
  **/
  public StateValues getState() {
    return state;
  }

  public void setState(StateValues state) {
    this.state = state;
  }


  public CustomerBillOnDemand lastUpdate(String lastUpdate) {
    this.lastUpdate = lastUpdate;
    return this;
  }

  /**
   * The last date time when the customer bill on demand has been updated
   * @return lastUpdate
  **/
  public String getLastUpdate() {
    return lastUpdate;
  }

  public void setLastUpdate(String lastUpdate) {
    this.lastUpdate = lastUpdate;
  }

  public CustomerBillOnDemand type(String type) {
    this.type = type;
    return this;
  }

  /**
   * Indicates the (class) type of the customer bill on demand request
   * @return type
  **/
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }

  public CustomerBillOnDemand schemaLocation(String schemaLocation) {
    this.schemaLocation = schemaLocation;
    return this;
  }

  /**
   * Link to the schema describing the REST resource
   * @return schemaLocation
  **/
  public String getSchemaLocation() {
    return schemaLocation;
  }

  public void setSchemaLocation(String schemaLocation) {
    this.schemaLocation = schemaLocation;
  }

  public CustomerBillOnDemand billingAccount(BillingAccountRef billingAccount) {
    this.billingAccount = billingAccount;
    return this;
  }

  /**
   * Reference of the billing account that produces the customer bill on demand
   * @return billingAccount
  **/
  public BillingAccountRef getBillingAccount() {
    return billingAccount;
  }

  public void setBillingAccount(BillingAccountRef billingAccount) {
    this.billingAccount = billingAccount;
  }

  public CustomerBillOnDemand relatedParty(RelatedPartyRef relatedParty) {
    this.relatedParty = relatedParty;
    return this;
  }

  /**
   * A related party for which the customer bill on demand is requested
   * @return relatedParty
  **/
  public RelatedPartyRef getRelatedParty() {
    return relatedParty;
  }

  public void setRelatedParty(RelatedPartyRef relatedParty) {
    this.relatedParty = relatedParty;
  }

  public CustomerBillOnDemand customerBill(BillRef customerBill) {
    this.customerBill = customerBill;
    return this;
  }

  /**
   * Reference of the bill generated by the customer bill on demand request
   * @return customerBill
  **/
  public BillRef getCustomerBill() {
    return customerBill;
  }

  public void setCustomerBill(BillRef customerBill) {
    this.customerBill = customerBill;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CustomerBillOnDemand customerBillOnDemand = (CustomerBillOnDemand) o;
    
    return Objects.equals(this.id, customerBillOnDemand.id) &&
        Objects.equals(this.href, customerBillOnDemand.href) &&
        Objects.equals(this.name, customerBillOnDemand.name) &&
        Objects.equals(this.description, customerBillOnDemand.description) &&
        Objects.equals(this.state, customerBillOnDemand.state) &&
        Objects.equals(this.lastUpdate, customerBillOnDemand.lastUpdate) &&
        Objects.equals(this.type, customerBillOnDemand.type) &&
        Objects.equals(this.schemaLocation, customerBillOnDemand.schemaLocation) &&
        Objects.equals(this.billingAccount, customerBillOnDemand.billingAccount) &&
        Objects.equals(this.relatedParty, customerBillOnDemand.relatedParty) &&
        Objects.equals(this.customerBill, customerBillOnDemand.customerBill);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, href, name, description, state, lastUpdate, type, 
    		schemaLocation, billingAccount, relatedParty, customerBill);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CustomerBillOnDemand {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    lastUpdate: ").append(toIndentedString(lastUpdate)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    schemaLocation: ").append(toIndentedString(schemaLocation)).append("\n");
    sb.append("    billingAccount: ").append(toIndentedString(billingAccount)).append("\n");
    sb.append("    relatedParty: ").append(toIndentedString(relatedParty)).append("\n");
    sb.append("    customerBill: ").append(toIndentedString(customerBill)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    
    return o.toString().replace("\n", "\n    ");
  }
  
}